# -*- coding: utf-8 -*-
"""streamlit_1.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L9BnZKk3b57k6-ogGHW96DLNY4E0moGU
"""

pip install streamlit

